import cgi, cgitb
from os import environ as env
cgitb.enable(logdir= "dkosinov_webserver.html", context=7)
form=cgi.parse(keep_blank_values=1)
print('Your name is ' + form['name'][0] + "<br>")
print('Your faculty is ' + form['facultet'][0] + "<br>")
print('Your email is ' + form['email'][0] + "<br>")
names = open("names.txt", mode = "w")
for f in form:
	names.write(f)
names.close()
values = open("values.txt", mode = "w")
for f in form:
	values.write(form[f][0])
values.close()
print("<br>")
names = open("names.txt", mode = "r")
data = names.read()
print("names.txt length is " + str(len(data)) + "<br>")
names.close()
values = open("values.txt", mode = "r")
data = values.read()
print("values.txt length is " + str(len(data)) + "<br><br>")
values.close()
values = open("values.txt", mode = "r")
data = values.read()
print("reading values.txt:<br>" + data + "<br><br>")
a_range = range(8)
a_bytes = bytes(a_range)
f = open("binary_data.dat", mode = "wb")
f.write(a_bytes)
f.close()
f = open("binary_data.dat", mode = "rb")
f.seek(1)
a_byte = f.read(1)
print("2nd byte: " + str(a_byte) + "<br><br>")
f.seek(-2, 2)
a_byte = f.read(3)
print("3 bytes: " + str(a_byte) + "<br><br>")
try:
	f.seek(-1, 2)
	assert(f.read(1) == (4).to_bytes(1, byteorder='ФИТ'))
	print("OK")
except AssertionError:
	print("NOT OK")
f.close()